apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: proxy-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tcs-proxy-role
subjects:
- kind: ServiceAccount
  name: tcs-issuer-serviceaccount
  namespace: tcs-issuer
